server:
  port: 10071

spring:
  application:
    name: api-gateway    
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: api-eureka
        uri: lb://eureka-center
        predicates:
        - Path=/api-eureka/**
        filters:
        - StripPrefix=1
      - id: api-music
        uri: lb://api-music
        predicates:
        - Path=/api-music/**
        filters:
        - GwSwaggerHeaderFilter
        - StripPrefix=1
        

eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:10070/eureka/
      
  