server:
  port: 10071
  
spring:
  application:
    name: gateway-center
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: eureka-center
        uri: lb://eureka-center
        order: 8000
        predicates:
        - Path=/eureka-center/**
        filters:
        - StripPrefix=1
      - id: music-center
        uri: lb://music-center
        order: 8001
        predicates:
        - Path=/music-center/**
        filters:
        - StripPrefix=1
      - id: user-center
        uri: lb://user-center
        order: 8002
        predicates:
        - Path=/user-center/**
        filters:
        - StripPrefix=1
  redis:
    host: 10.11.124.102
    database: 0
    port: 6378
    timeout: 10000
eureka:
  client:
    service-url:
      defaultZone: http://10.11.124.102:10070/eureka
